# Generated by Django 5.1.4 on 2024-12-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('РЗ', 'для регионального займа'), ('СЗ', 'для совместного займа')], max_length=70)),
                ('program', models.CharField(choices=[('ПР', 'Проекты развития с регфондами'), ('КИ', 'Комплектующие изделия с регфондами'), ('ПТ', 'Производительность труда с регфондами'), ('ПЛП', 'Проекты лесной промышленности с регфондами'), ('РПР', 'Региональные проекты развития')], max_length=70)),
                ('cost', models.DecimalField(decimal_places=1, max_digits=9)),
                ('buyer', models.ManyToManyField(related_name='Service', to='financial_analyst.buyer')),
            ],
        ),
    ]
