# Generated by Django 5.1.4 on 2024-12-17 08:47

import django.views.generic.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analyst', '0002_alter_buyer_options_buyer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(default=django.views.generic.dates.timezone_today, verbose_name='Имя'),
        ),
    ]
