# Generated by Django 5.1.4 on 2024-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analyst', '0004_alter_buyer_options_alter_buyer_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='buyer',
            field=models.ManyToManyField(related_name='Service', to='financial_analyst.buyer', verbose_name='Покупатели'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='program',
            field=models.CharField(choices=[('ПР', 'Проекты развития с регфондами'), ('КИ', 'Комплектующие изделия с регфондами'), ('ПТ', 'Производительность труда с регфондами'), ('ПЛП', 'Проекты лесной промышленности с регфондами'), ('РПР', 'Региональные проекты развития')], max_length=70, verbose_name='Программа займа'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('РЗ', 'для регионального займа'), ('СЗ', 'для совместного займа')], max_length=70, verbose_name='Вид займа'),
        ),
    ]
