# Generated by Django 5.1.4 on 2024-12-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analyst', '0005_alter_service_options_alter_buyer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='program',
            field=models.CharField(choices=[('Проекты развития с регфондами', 'Проекты развития с регфондами'), ('Комплектующие изделия с регфондами', 'Комплектующие изделия с регфондами'), ('Производительность труда с регфондами', 'Производительность труда с регфондами'), ('Проекты лесной промышленности с регфондами', 'Проекты лесной промышленности с регфондами'), ('Региональные проекты развития', 'Региональные проекты развития')], max_length=70, verbose_name='Программа займа'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('для регионального займа', 'для регионального займа'), ('для совместного займа', 'для совместного займа')], max_length=70, verbose_name='Вид займа'),
        ),
    ]
